Repository cloudreach/aws-lambda-es-cleanup, pull requests merged in 2020-04, with the labels that each got.

#37 Fix Logic, Improve Test Coverage, and Resilience
  README.md
  es_cleanup.py
  es_cleanup_test.py
  serverless.yml
  terraform/lambda.tf
Labels: enhancement, in review

#38 Make lambda timeout a variable
  terraform/README.md
  terraform/lambda.tf
  terraform/variables.tf
Labels: enhancement

#41 Infrastructure test deployment
  tests/README.md
  tests/data.tf
  tests/main.tf
  tests/main_vpc.tf
  tests/outputs.tf
  tests/run.sh
  tests/variables.tf
Labels: enhancement

#42 Update README.md
  README.md
Labels: bug
